name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
 
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Debug git
        run: |
          git --version
          git remote -v
          git branch -a

      - name: Simulate git push (debug)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          echo "--- git config ---"
          git config --list
          echo "--- remote URL (masked) ---"
          git remote -v | sed -E 's#(https://)[^@]+@#\1***@#g'
          echo "--- fetch gh-pages (may fail if missing) ---"
          git fetch origin gh-pages || echo 'fetch gh-pages failed (branch may not exist)'
          echo "--- attempt dry-run push to gh-pages (will not change remote) ---"
          # Use token-authenticated URL to ensure we exercise push auth
          git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}"
          git push --dry-run origin HEAD:gh-pages || echo 'dry-run push failed (see exit code)'
          echo "--- end simulate ---"

      - name: Deploy (gh-pages)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          allow_empty_commit: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
